// 通用写作 - 第二层分类
export const generalWritingCategories = [
  { id: "workplace", label: "职场办公" },
  { id: "government", label: "政务公文" },
];

// 职场办公 - 第三层分类
export const workplaceSubCategories = [
  { id: "communication", label: "沟通协作" },
  { id: "reports", label: "汇报总结" },
  { id: "speeches", label: "演讲发言" },
  { id: "team-management", label: "团队管理" },
  { id: "project-management", label: "项目管理" },
  { id: "personal-development", label: "个人发展" },
];

// 政务公文 - 第三层分类
export const governmentSubCategories = [
  { id: "government-affairs", label: "政务公文" },
  { id: "administrative", label: "事务公文" },
  { id: "publicity", label: "宣传公文" },
  { id: "communication-docs", label: "通信公文" },
  { id: "etiquette", label: "礼仪公文" },
];

// ========== 职场办公模板 ==========

// 沟通协作模板
export const communicationTemplates = [
  {
    id: 1001,
    icon: "📧",
    title: "会议邀请函",
    desc: "撰写一份内容完整、语言得体、格式规范的会议邀请函，确保参会人员能够清楚了解会议的主题、时间、地点、议程等重要信息，并产生参加会议的兴趣。",
    color: "bg-blue-500",
  },
  {
    id: 1002,
    icon: "📝",
    title: "会议纪要",
    desc: "帮助用户掌握会议纪要的撰写方法，提高信息传达的准确性和效率。",
    color: "bg-green-500",
  },
  {
    id: 1003,
    icon: "💬",
    title: "工作邮件",
    desc: "设计一个能够帮助用户掌握工作邮件撰写要点和技巧的提示词。",
    color: "bg-purple-500",
  },
  {
    id: 1004,
    icon: "📢",
    title: "内部通知",
    desc: "帮助用户掌握内部通知的写作技巧，能够撰写清晰、准确、有效的内部通知。",
    color: "bg-orange-500",
  },
  {
    id: 1005,
    icon: "📣",
    title: "外部通知",
    desc: "撰写一份全面、专业的《外部通知》写作指南，帮助用户掌握外部通知的写作要点和技巧。",
    color: "bg-red-500",
  },
  {
    id: 1006,
    icon: "📋",
    title: "客户反馈报告",
    desc: "撰写一份全面、准确、有价值的客户反馈报告，为企业决策提供依据。",
    color: "bg-yellow-500",
  },
  {
    id: 1007,
    icon: "📊",
    title: "员工满意度调查报告",
    desc: "撰写一份全面、准确、有价值的员工满意度调查报告，为企业决策提供参考。",
    color: "bg-indigo-500",
  },
  {
    id: 1008,
    icon: "📞",
    title: "紧急情况联络表",
    desc: "制作一份详细且实用的《紧急情况联络表》，确保在紧急情况下能够快速、有效地进行联络。",
    color: "bg-pink-500",
  },
  {
    id: 1009,
    icon: "📄",
    title: "日常工作报告",
    desc: "帮助用户掌握日常工作报告的写作方法，提高报告的质量和效果。",
    color: "bg-teal-500",
  },
  {
    id: 1010,
    icon: "🔍",
    title: "问题解决报告",
    desc: "帮助用户掌握问题解决报告的撰写方法，使其能够清晰、有效地阐述问题及解决方案。",
    color: "bg-cyan-500",
  },
  {
    id: 1011,
    icon: "💡",
    title: "建议书",
    desc: "帮助用户掌握建议书的写作方法和技巧，提高建议书的质量和效果。",
    color: "bg-lime-500",
  },
  {
    id: 1012,
    icon: "💐",
    title: "感谢信",
    desc: "为用户提供一份详细的感谢信写作指南，帮助用户写出真挚、恰当的感谢信。",
    color: "bg-amber-500",
  },
  {
    id: 1013,
    icon: "🙏",
    title: "道歉信",
    desc: "为用户提供专业的道歉信写作指导，帮助用户写出真诚、恰当、有效的道歉信。",
    color: "bg-violet-500",
  },
];

// 汇报总结模板
export const reportsTemplates = [
  {
    id: 1101,
    icon: "📊",
    title: "周/月/季度工作总结",
    desc: "为用户提供详细、实用的《周/月/季度工作总结》撰写指南。",
    color: "bg-blue-500",
  },
  {
    id: 1102,
    icon: "📋",
    title: "周/月/季度工作计划",
    desc: "帮助用户掌握《周/月/季度工作计划》的撰写技巧，提供详细、实用的写作指导。",
    color: "bg-green-500",
  },
  {
    id: 1103,
    icon: "📈",
    title: "项目进度报告",
    desc: "编写一份详细、清晰的项目进度报告，使相关人员能够快速了解项目的进展情况、存在的问题及解决方案。",
    color: "bg-purple-500",
  },
  {
    id: 1104,
    icon: "💰",
    title: "销售业绩报告",
    desc: "撰写一份全面、客观、具有洞察力的销售业绩报告，为企业决策提供有力支持。",
    color: "bg-orange-500",
  },
  {
    id: 1105,
    icon: "💵",
    title: "财务报告",
    desc: "编写一份结构清晰、内容准确、易于理解的财务报告，满足读者对财务信息的需求。",
    color: "bg-red-500",
  },
  {
    id: 1106,
    icon: "📊",
    title: "市场分析报告",
    desc: "撰写一份全面、准确、具有洞察力的市场分析报告，为企业决策提供依据。",
    color: "bg-indigo-500",
  },
  {
    id: 1107,
    icon: "📝",
    title: "年度述职报告",
    desc: "帮助用户撰写一份内容全面、结构清晰、重点突出的年度述职报告。",
    color: "bg-pink-500",
  },
  {
    id: 1108,
    icon: "📄",
    title: "转正述职报告",
    desc: "帮助用户撰写一份内容全面、结构清晰、重点突出的转正述职报告，以提高用户通过转正评估的成功率。",
    color: "bg-teal-500",
  },
  {
    id: 1109,
    icon: "📑",
    title: "绩效评估报告",
    desc: "撰写一份详细、准确、客观的绩效评估报告，为企业的人力资源管理提供有力的支持。",
    color: "bg-cyan-500",
  },
  {
    id: 1110,
    icon: "🎯",
    title: "绩效改进计划",
    desc: "撰写一份详细、实用的绩效改进计划，帮助员工明确改进方向和步骤。",
    color: "bg-yellow-500",
  },
  {
    id: 1111,
    icon: "📰",
    title: "部门简报",
    desc: "帮助用户掌握部门简报的写作方法，提高信息传达的效果和效率。",
    color: "bg-lime-500",
  },
  {
    id: 1112,
    icon: "📈",
    title: "业务发展计划",
    desc: "撰写一份高质量的《业务发展计划》，为企业的业务发展提供明确的方向和可行的策略。",
    color: "bg-amber-500",
  },
];

// 演讲发言模板
export const speechesTemplates = [
  {
    id: 1201,
    icon: "👋",
    title: "入职欢迎辞",
    desc: "撰写一篇热情、友好且具有引导性的入职欢迎辞，让新员工感受到公司的温暖和期待。",
    color: "bg-blue-500",
  },
  {
    id: 1202,
    icon: "🏢",
    title: "部门介绍演讲",
    desc: "创作一份能够全面、准确地介绍部门情况，提升部门形象和影响力的演讲内容。",
    color: "bg-green-500",
  },
  {
    id: 1203,
    icon: "🚀",
    title: "项目启动演讲",
    desc: "撰写一份能够清晰传达项目信息、激发团队热情、获得相关利益者支持的项目启动演讲。",
    color: "bg-purple-500",
  },
  {
    id: 1204,
    icon: "🎯",
    title: "团队建设活动开场白",
    desc: "创作一篇能够吸引参与者注意力、激发他们积极参与团队建设活动的开场白。",
    color: "bg-orange-500",
  },
  {
    id: 1205,
    icon: "📊",
    title: "年终总结大会发言稿",
    desc: "创作一篇结构清晰、内容充实、语言得体的年终总结大会发言稿，能够有效传达信息，激发员工的积极性。",
    color: "bg-red-500",
  },
  {
    id: 1206,
    icon: "🎉",
    title: "年会发言稿",
    desc: "帮助用户撰写一篇结构清晰、内容丰富、富有感染力的年会发言稿。",
    color: "bg-indigo-500",
  },
  {
    id: 1207,
    icon: "🏆",
    title: "表彰大会发言稿",
    desc: "撰写一篇能够充分肯定获奖者的成就，激发全体员工积极性的表彰大会发言稿。",
    color: "bg-pink-500",
  },
  {
    id: 1208,
    icon: "👴",
    title: "退休告别信/演讲",
    desc: "帮助用户撰写一篇感人至深、充满回忆和展望的退休告别信或演讲，让用户能够以积极的态度告别职业生涯，同时表达对同事和公司的感激之情。",
    color: "bg-teal-500",
  },
  {
    id: 1209,
    icon: "💪",
    title: "销售激励演讲",
    desc: "创作一篇具有感染力和号召力的销售激励演讲，激发销售团队的斗志，提升销售业绩。",
    color: "bg-cyan-500",
  },
  {
    id: 1210,
    icon: "🌟",
    title: "公司文化宣讲",
    desc: "撰写一份能够清晰、准确地传达公司文化的宣讲文档，激发员工对公司文化的认同和践行。",
    color: "bg-yellow-500",
  },
  {
    id: 1211,
    icon: "📝",
    title: "入职发言稿",
    desc: "帮助用户撰写一篇结构清晰、内容充实、语言得体的入职发言稿。",
    color: "bg-lime-500",
  },
  {
    id: 1212,
    icon: "🎤",
    title: "转正述职报告演讲稿",
    desc: "帮助用户撰写一份内容充实、结构清晰、语言得体的转正述职报告演讲稿，以提高用户转正的成功率。",
    color: "bg-amber-500",
  },
];

// 团队管理模板
export const teamManagementTemplates = [
  {
    id: 1301,
    icon: "📢",
    title: "招聘广告",
    desc: "撰写一份吸引人且信息准确的招聘广告，帮助企业找到合适的人才。",
    color: "bg-blue-500",
  },
  {
    id: 1302,
    icon: "📋",
    title: "职位描述",
    desc: "创作一份详细、准确且具有吸引力的职位描述，以满足企业的招聘需求和潜在求职者的信息需求。",
    color: "bg-green-500",
  },
  {
    id: 1303,
    icon: "📧",
    title: "面试邀请",
    desc: "撰写一份专业、吸引人的面试邀请，提高候选人的参与度和对公司的好感度。",
    color: "bg-purple-500",
  },
  {
    id: 1304,
    icon: "📝",
    title: "面试反馈表",
    desc: "设计一份全面、客观、准确的面试反馈表，为招聘决策提供有力支持。",
    color: "bg-orange-500",
  },
  {
    id: 1305,
    icon: "✅",
    title: "录用通知书",
    desc: "撰写一份清晰、准确、专业的录用通知书，确保被录用者能够清楚了解录用相关信息。",
    color: "bg-red-500",
  },
  {
    id: 1306,
    icon: "📖",
    title: "入职手册",
    desc: "编写一份全面、清晰、实用的入职手册，帮助新员工快速适应公司环境和工作要求。",
    color: "bg-indigo-500",
  },
  {
    id: 1307,
    icon: "📄",
    title: "离职手续说明",
    desc: "撰写一份详细、准确、易懂的离职手续说明，帮助员工顺利办理离职。",
    color: "bg-pink-500",
  },
  {
    id: 1308,
    icon: "🎯",
    title: "职业发展规划",
    desc: "为用户提供一份全面、系统且具有实际操作性的职业发展规划写作指南。",
    color: "bg-teal-500",
  },
  {
    id: 1309,
    icon: "📊",
    title: "员工培训记录",
    desc: "设计一份全面的《员工培训记录》，帮助员工提升职场写作能力。",
    color: "bg-cyan-500",
  },
  {
    id: 1310,
    icon: "⬆️",
    title: "内部晋升申请",
    desc: "帮助用户撰写一份内容充实、结构清晰、能够突出个人优势和潜力的内部晋升申请。",
    color: "bg-yellow-500",
  },
  {
    id: 1311,
    icon: "🔄",
    title: "转岗申请书",
    desc: "帮助用户撰写一份内容完整、语言得体、逻辑清晰的转岗申请书，提高转岗申请的成功率。",
    color: "bg-lime-500",
  },
  {
    id: 1312,
    icon: "🏖️",
    title: "请假申请表",
    desc: "设计一个符合职场规范且易于填写的《请假申请表》模板，并提供填写指南。",
    color: "bg-amber-500",
  },
  {
    id: 1313,
    icon: "⏰",
    title: "加班申请表",
    desc: "设计一个清晰、准确、完整的加班申请表，满足企业管理和员工需求。",
    color: "bg-violet-500",
  },
  {
    id: 1314,
    icon: "✈️",
    title: "出差申请表",
    desc: "设计一个全面、准确且符合公司规定的出差申请表模板，并提供填写指南。",
    color: "bg-rose-500",
  },
  {
    id: 1315,
    icon: "🎁",
    title: "员工福利申请",
    desc: "撰写一份清晰、合理、有说服力的员工福利申请，以提高申请成功的可能性。",
    color: "bg-sky-500",
  },
  {
    id: 1316,
    icon: "📑",
    title: "工作交接文档",
    desc: "撰写一份完整、清晰、易于理解的工作交接文档，确保接手人员能够快速熟悉工作内容和流程。",
    color: "bg-emerald-500",
  },
];

// 项目管理模板
export const projectManagementTemplates = [
  {
    id: 1401,
    icon: "🚀",
    title: "项目启动报告",
    desc: "撰写一份详细、准确、具有说服力的项目启动报告，为项目的顺利启动和实施提供有力支持。",
    color: "bg-blue-500",
  },
  {
    id: 1402,
    icon: "📋",
    title: "项目计划书",
    desc: "为用户提供一份详细、专业且实用的项目计划书写作指南，帮助用户顺利完成项目计划书的撰写。",
    color: "bg-green-500",
  },
  {
    id: 1403,
    icon: "📊",
    title: "项目进度跟踪表",
    desc: "设计一个全面、实用的《项目进度跟踪表》，帮助项目团队清晰了解项目进度，及时发现问题并采取措施进行调整。",
    color: "bg-purple-500",
  },
  {
    id: 1404,
    icon: "💬",
    title: "项目沟通计划",
    desc: "制定一份详细、全面的《项目沟通计划》，确保项目信息的准确、及时传递，提高项目团队的协作效率，减少沟通障碍和误解。",
    color: "bg-orange-500",
  },
  {
    id: 1405,
    icon: "✅",
    title: "项目验收报告",
    desc: "撰写一份全面、准确的项目验收报告，为项目的验收提供有力依据。",
    color: "bg-red-500",
  },
  {
    id: 1406,
    icon: "📈",
    title: "项目后评价报告",
    desc: "撰写一份详细、准确、具有参考价值的项目后评价报告。",
    color: "bg-indigo-500",
  },
];

// 个人发展模板
export const personalDevelopmentTemplates = [
  {
    id: 1501,
    icon: "📝",
    title: "求职简历优化",
    desc: "帮助求职者优化简历，提高其在求职过程中的竞争力，增加获得面试机会的可能性。",
    color: "bg-blue-500",
  },
  {
    id: 1502,
    icon: "📄",
    title: "简历优化",
    desc: "提供全面、专业的简历优化方案，帮助求职者提升简历的质量和吸引力。",
    color: "bg-green-500",
  },
  {
    id: 1503,
    icon: "✉️",
    title: "求职信",
    desc: "为求职者提供一份详细且实用的求职信写作指南，帮助他们提高求职信的质量和效果。",
    color: "bg-purple-500",
  },
  {
    id: 1504,
    icon: "🌱",
    title: "个人成长计划",
    desc: "为用户提供一份详细且实用的《个人成长计划》写作指南，帮助用户清晰地规划自己的职业发展路径。",
    color: "bg-orange-500",
  },
  {
    id: 1505,
    icon: "📚",
    title: "技能提升计划",
    desc: "制定一份全面的职场写作技能提升计划，帮助用户提高写作水平。",
    color: "bg-red-500",
  },
  {
    id: 1506,
    icon: "👋",
    title: "自我介绍",
    desc: "设计一个能够帮助学习者掌握自我介绍写作技巧的提示词，使他们能够写出清晰、简洁、有吸引力的自我介绍。",
    color: "bg-indigo-500",
  },
  {
    id: 1507,
    icon: "🎯",
    title: "职业发展规划",
    desc: "为用户提供一份全面、系统且具有实际操作性的职业发展规划写作指南。",
    color: "bg-pink-500",
  },
  {
    id: 1508,
    icon: "🎪",
    title: "个人目标设定",
    desc: "创作一份关于《个人目标设定》的详细且实用的职场写作内容，帮助读者掌握有效的个人目标设定方法。",
    color: "bg-teal-500",
  },
  {
    id: 1509,
    icon: "📊",
    title: "能力评估报告",
    desc: "撰写一份全面、客观、准确的能力评估报告，为员工的发展和企业的管理提供有价值的参考。",
    color: "bg-cyan-500",
  },
  {
    id: 1510,
    icon: "📖",
    title: "学习资源清单",
    desc: "制定一份详细的《职场写作学习资源清单》，帮助学习者系统地提升写作能力。",
    color: "bg-yellow-500",
  },
  {
    id: 1511,
    icon: "🎓",
    title: "职业资格证书申请",
    desc: "撰写一份符合职业资格证书申请要求的文档，确保申请人的信息准确、完整，申请理由充分、合理。",
    color: "bg-lime-500",
  },
  {
    id: 1512,
    icon: "📚",
    title: "继续教育计划",
    desc: "撰写一份详细、实用的《继续教育计划》，以满足员工的学习需求和企业的发展要求。",
    color: "bg-amber-500",
  },
  {
    id: 1513,
    icon: "👨‍🏫",
    title: "导师指导计划",
    desc: "设计一套全面的导师指导计划，帮助学员提高职场写作水平。",
    color: "bg-violet-500",
  },
  {
    id: 1514,
    icon: "📔",
    title: "自我反思日记",
    desc: "设计一个能够引导用户进行深入自我反思并有效记录的《自我反思日记》模板。",
    color: "bg-rose-500",
  },
  {
    id: 1515,
    icon: "🔄",
    title: "职业转型规划",
    desc: "撰写一份详细、全面的《职业转型规划》，帮助读者明确职业转型的目标、步骤和方法，提高职业转型的成功率。",
    color: "bg-sky-500",
  },
  {
    id: 1516,
    icon: "🌟",
    title: "个人品牌建立指南",
    desc: "编写一份全面的《个人品牌建立指南》，帮助读者通过职场写作提升个人品牌形象。",
    color: "bg-emerald-500",
  },
  {
    id: 1517,
    icon: "⏰",
    title: "时间管理计划",
    desc: "撰写一份详细且实用的《时间管理计划》，帮助职场人士合理安排工作时间，提高工作效率。",
    color: "bg-fuchsia-500",
  },
  {
    id: 1518,
    icon: "📈",
    title: "目标达成追踪表",
    desc: "设计一个全面且易于使用的《目标达成追踪表》，帮助用户清晰地了解目标的进展情况，并及时采取必要的行动。",
    color: "bg-slate-500",
  },
  {
    id: 1519,
    icon: "👑",
    title: "领导力培养计划",
    desc: "设计一个全面的《领导力培养计划》，通过职场写作的方式帮助学员提升领导力素质和能力。",
    color: "bg-zinc-500",
  },
];

// ========== 政务公文模板 ==========

// 政务公文模板
export const governmentAffairsTemplates = [
  {
    id: 2001,
    icon: "📜",
    title: "决议",
    desc: "撰写一份全面、准确、具有可操作性的政务决议。",
    color: "bg-blue-500",
  },
  {
    id: 2002,
    icon: "📑",
    title: "决定",
    desc: "撰写一份内容准确、条理清晰、具有可操作性的政务《决定》。",
    color: "bg-green-500",
  },
  {
    id: 2003,
    icon: "⚡",
    title: "命令（令）",
    desc: "撰写符合规范、内容准确、具有权威性的命令（令）。",
    color: "bg-purple-500",
  },
  {
    id: 2004,
    icon: "📰",
    title: "公报",
    desc: "撰写一份准确、清晰、全面的政务公报，满足公众对政府信息的需求。",
    color: "bg-orange-500",
  },
  {
    id: 2005,
    icon: "📢",
    title: "公告",
    desc: "撰写一份准确、清晰、简洁的政务公告，确保公众能够准确理解公告内容。",
    color: "bg-red-500",
  },
  {
    id: 2006,
    icon: "📣",
    title: "通告",
    desc: "撰写一份清晰、准确、具有权威性的政务通告，确保公众能够理解并遵守通告内容。",
    color: "bg-indigo-500",
  },
  {
    id: 2007,
    icon: "⚖️",
    title: "意见",
    desc: "撰写一份全面、准确、具有可操作性的政务《意见》。",
    color: "bg-pink-500",
  },
  {
    id: 2008,
    icon: "📄",
    title: "通知",
    desc: "撰写一份符合政务工作要求、内容准确、条理清晰的通知。",
    color: "bg-teal-500",
  },
  {
    id: 2009,
    icon: "📋",
    title: "通报",
    desc: "撰写一份符合政务工作规范的通报，准确传达相关信息。",
    color: "bg-cyan-500",
  },
  {
    id: 2010,
    icon: "📝",
    title: "报告",
    desc: "撰写一份全面、准确、清晰的政务报告，为上级决策提供有力依据。",
    color: "bg-yellow-500",
  },
  {
    id: 2011,
    icon: "📃",
    title: "请示",
    desc: "设计一个能够帮助用户了解并掌握政务工作中《请示》的写作要点的提示词。",
    color: "bg-lime-500",
  },
  {
    id: 2012,
    icon: "✅",
    title: "批复",
    desc: "撰写一份符合规范、内容准确、表达清晰的政务批复。",
    color: "bg-amber-500",
  },
  {
    id: 2013,
    icon: "📊",
    title: "议案",
    desc: "撰写一份具有针对性、可行性和前瞻性的政务议案，为政府决策提供有力支持。",
    color: "bg-violet-500",
  },
  {
    id: 2014,
    icon: "✉️",
    title: "函",
    desc: "帮助用户了解并掌握政务工作中函的写作方法，提供详细的函件写作指导。",
    color: "bg-rose-500",
  },
  {
    id: 2015,
    icon: "📔",
    title: "纪要",
    desc: "撰写一份全面、准确、清晰的政务纪要，反映会议的主要内容和决策结果。",
    color: "bg-sky-500",
  },
];

// 事务公文模板
export const administrativeTemplates = [
  {
    id: 2101,
    icon: "📊",
    title: "汇报材料",
    desc: "撰写一份全面、准确、有针对性的政务汇报材料，为上级决策提供依据。",
    color: "bg-blue-500",
  },
  {
    id: 2102,
    icon: "🔍",
    title: "检查报告",
    desc: "撰写一份全面、准确、具有针对性的政务工作检查报告。",
    color: "bg-green-500",
  },
  {
    id: 2103,
    icon: "📋",
    title: "督查通报",
    desc: "撰写一份全面、准确、客观的督查通报，反映工作实际情况，提出改进建议。",
    color: "bg-purple-500",
  },
  {
    id: 2104,
    icon: "📈",
    title: "评估报告",
    desc: "撰写一份全面、客观、准确的政务工作评估报告。",
    color: "bg-orange-500",
  },
  {
    id: 2105,
    icon: "🚨",
    title: "应急预案",
    desc: "制定一份全面、实用的政务应急预案，提高应对突发事件的能力。",
    color: "bg-red-500",
  },
  {
    id: 2106,
    icon: "📑",
    title: "项目申请书",
    desc: "撰写一份全面、详细、符合政务工作要求的项目申请书，确保项目能够得到顺利审批和实施。",
    color: "bg-indigo-500",
  },
  {
    id: 2107,
    icon: "📝",
    title: "合同协议",
    desc: "撰写一份严谨、完整、符合政务工作要求的合同协议。",
    color: "bg-pink-500",
  },
  {
    id: 2108,
    icon: "⚖️",
    title: "法律意见书",
    desc: "撰写一份全面、准确、具有可操作性的法律意见书，为政务工作提供有力的法律支持。",
    color: "bg-teal-500",
  },
  {
    id: 2109,
    icon: "📅",
    title: "工作计划",
    desc: "制定一份全面、具体、可操作的政务工作计划，确保各项政务工作的顺利进行，提高政府的工作效能和公众满意度。",
    color: "bg-cyan-500",
  },
  {
    id: 2110,
    icon: "📊",
    title: "工作总结",
    desc: "撰写一份全面、客观、准确的政务工作总结，为后续工作提供参考和指导。",
    color: "bg-yellow-500",
  },
  {
    id: 2111,
    icon: "🔎",
    title: "调研报告",
    desc: "撰写一份全面、准确、具有参考价值的政务调研报告。",
    color: "bg-lime-500",
  },
  {
    id: 2112,
    icon: "📔",
    title: "会议纪要",
    desc: "撰写一份全面、准确、清晰的政务会议纪要，确保会议精神得到有效传达和落实。",
    color: "bg-amber-500",
  },
];

// 宣传公文模板
export const publicityTemplates = [
  {
    id: 2201,
    icon: "📢",
    title: "新闻稿",
    desc: "撰写政务新闻，宣传重要工作和成就。",
    color: "bg-blue-500",
  },
  {
    id: 2202,
    icon: "📰",
    title: "简报",
    desc: "编写工作简报，及时反映工作动态。",
    color: "bg-green-500",
  },
  {
    id: 2203,
    icon: "🎙️",
    title: "宣传方案",
    desc: "制定宣传策划，扩大工作影响力。",
    color: "bg-purple-500",
  },
  {
    id: 2204,
    icon: "📝",
    title: "经验材料",
    desc: "总结推广先进经验和典型做法。",
    color: "bg-orange-500",
  },
  {
    id: 2205,
    icon: "🌟",
    title: "典型事迹",
    desc: "宣传先进人物和典型事迹。",
    color: "bg-red-500",
  },
  {
    id: 2206,
    icon: "📣",
    title: "倡议书",
    desc: "发起倡议，号召群众参与和支持。",
    color: "bg-indigo-500",
  },
];

// 通信公文模板
export const communicationDocsTemplates = [
  {
    id: 2301,
    icon: "✉️",
    title: "函",
    desc: "用于不相隶属机关之间商洽工作、询问和答复问题。",
    color: "bg-blue-500",
  },
  {
    id: 2302,
    icon: "💬",
    title: "便函",
    desc: "用于日常工作联系的简便函件。",
    color: "bg-green-500",
  },
  {
    id: 2303,
    icon: "📧",
    title: "联系函",
    desc: "用于单位之间联系具体事务。",
    color: "bg-purple-500",
  },
  {
    id: 2304,
    icon: "🤝",
    title: "协商函",
    desc: "用于就某项工作与其他单位协商。",
    color: "bg-orange-500",
  },
  {
    id: 2305,
    icon: "📮",
    title: "邀请函",
    desc: "邀请相关单位或人员参加活动。",
    color: "bg-red-500",
  },
];

// 礼仪公文模板
export const etiquetteTemplates = [
  {
    id: 2401,
    icon: "🎉",
    title: "贺信",
    desc: "向单位或个人表示祝贺。",
    color: "bg-blue-500",
  },
  {
    id: 2402,
    icon: "🎊",
    title: "贺电",
    desc: "以电报形式表达祝贺之意。",
    color: "bg-green-500",
  },
  {
    id: 2403,
    icon: "🙏",
    title: "慰问信",
    desc: "向有关单位或个人表示慰问。",
    color: "bg-purple-500",
  },
  {
    id: 2404,
    icon: "💐",
    title: "感谢信",
    desc: "对给予帮助和支持的单位或个人表示感谢。",
    color: "bg-orange-500",
  },
  {
    id: 2405,
    icon: "🕊️",
    title: "唁电",
    desc: "对逝者表示哀悼，对家属表示慰问。",
    color: "bg-gray-500",
  },
  {
    id: 2406,
    icon: "🎈",
    title: "欢迎词",
    desc: "欢迎来访客人，表达友好情谊。",
    color: "bg-pink-500",
  },
  {
    id: 2407,
    icon: "👋",
    title: "欢送词",
    desc: "欢送离别客人，表达惜别之情。",
    color: "bg-indigo-500",
  },
  {
    id: 2408,
    icon: "🎤",
    title: "答谢词",
    desc: "对他人的关心和帮助表示感谢。",
    color: "bg-teal-500",
  },
  {
    id: 2409,
    icon: "🎓",
    title: "祝酒词",
    desc: "在宴会等场合发表祝酒讲话。",
    color: "bg-cyan-500",
  },
];
