// 通用写作 - 第二层分类
export const generalWritingCategories = [
  { id: "workplace", label: "职场办公" },
  { id: "government", label: "政务公文" },
];

// 职场办公 - 第三层分类
export const workplaceSubCategories = [
  { id: "communication", label: "沟通协作" },
  { id: "reports", label: "汇报总结" },
  { id: "speeches", label: "演讲发言" },
  { id: "team-management", label: "团队管理" },
  { id: "project-management", label: "项目管理" },
  { id: "personal-development", label: "个人发展" },
];

// 政务公文 - 第三层分类
export const governmentSubCategories = [
  { id: "government-affairs", label: "政务公文" },
  { id: "administrative", label: "事务公文" },
  { id: "publicity", label: "宣传公文" },
  { id: "communication-docs", label: "通信公文" },
  { id: "etiquette", label: "礼仪公文" },
];

// ========== 职场办公模板 ==========

// 沟通协作模板
export const communicationTemplates = [
  {
    id: 1001,
    icon: "📧",
    title: "会议邀请函",
    desc: "撰写一份内容完整、语言得体、格式规范的会议邀请函，确保参会人员能够清楚了解会议的主题、时间、地点、议程等重要信息，并产生参加会议的兴趣。",
    color: "bg-blue-500",
  },
  {
    id: 1002,
    icon: "📝",
    title: "会议纪要",
    desc: "帮助用户掌握会议纪要的撰写方法，提高信息传达的准确性和效率。",
    color: "bg-green-500",
  },
  {
    id: 1003,
    icon: "💬",
    title: "工作邮件",
    desc: "设计一个能够帮助用户掌握工作邮件撰写要点和技巧的提示词。",
    color: "bg-purple-500",
  },
  {
    id: 1004,
    icon: "📢",
    title: "内部通知",
    desc: "帮助用户掌握内部通知的写作技巧，能够撰写清晰、准确、有效的内部通知。",
    color: "bg-orange-500",
  },
  {
    id: 1005,
    icon: "📣",
    title: "外部通知",
    desc: "撰写一份全面、专业的《外部通知》写作指南，帮助用户掌握外部通知的写作要点和技巧。",
    color: "bg-red-500",
  },
  {
    id: 1006,
    icon: "📋",
    title: "客户反馈报告",
    desc: "撰写一份全面、准确、有价值的客户反馈报告，为企业决策提供依据。",
    color: "bg-yellow-500",
  },
  {
    id: 1007,
    icon: "📊",
    title: "员工满意度调查报告",
    desc: "撰写一份全面、准确、有价值的员工满意度调查报告，为企业决策提供参考。",
    color: "bg-indigo-500",
  },
  {
    id: 1008,
    icon: "📞",
    title: "紧急情况联络表",
    desc: "制作一份详细且实用的《紧急情况联络表》，确保在紧急情况下能够快速、有效地进行联络。",
    color: "bg-pink-500",
  },
  {
    id: 1009,
    icon: "📄",
    title: "日常工作报告",
    desc: "帮助用户掌握日常工作报告的写作方法，提高报告的质量和效果。",
    color: "bg-teal-500",
  },
  {
    id: 1010,
    icon: "🔍",
    title: "问题解决报告",
    desc: "帮助用户掌握问题解决报告的撰写方法，使其能够清晰、有效地阐述问题及解决方案。",
    color: "bg-cyan-500",
  },
  {
    id: 1011,
    icon: "💡",
    title: "建议书",
    desc: "帮助用户掌握建议书的写作方法和技巧，提高建议书的质量和效果。",
    color: "bg-lime-500",
  },
  {
    id: 1012,
    icon: "💐",
    title: "感谢信",
    desc: "为用户提供一份详细的感谢信写作指南，帮助用户写出真挚、恰当的感谢信。",
    color: "bg-amber-500",
  },
  {
    id: 1013,
    icon: "🙏",
    title: "道歉信",
    desc: "为用户提供专业的道歉信写作指导，帮助用户写出真诚、恰当、有效的道歉信。",
    color: "bg-violet-500",
  },
];

// 汇报总结模板
export const reportsTemplates = [
  {
    id: 1101,
    icon: "📈",
    title: "周工作总结",
    desc: "总结一周工作成果、问题和下周计划。",
    color: "bg-blue-500",
  },
  {
    id: 1102,
    icon: "📊",
    title: "月度工作总结",
    desc: "全面回顾月度工作，分析成效和改进方向。",
    color: "bg-green-500",
  },
  {
    id: 1103,
    icon: "📉",
    title: "季度工作总结",
    desc: "梳理季度工作亮点、数据和发展趋势。",
    color: "bg-purple-500",
  },
  {
    id: 1104,
    icon: "📋",
    title: "年度工作总结",
    desc: "全面总结年度工作成就、经验和未来规划。",
    color: "bg-orange-500",
  },
  {
    id: 1105,
    icon: "🎯",
    title: "项目总结报告",
    desc: "总结项目执行情况、成果和经验教训。",
    color: "bg-red-500",
  },
  {
    id: 1106,
    icon: "💼",
    title: "述职报告",
    desc: "全面展示个人工作业绩、能力和发展规划。",
    color: "bg-indigo-500",
  },
  {
    id: 1107,
    icon: "📝",
    title: "实习总结报告",
    desc: "总结实习期间的学习收获和成长经历。",
    color: "bg-pink-500",
  },
  {
    id: 1108,
    icon: "🔍",
    title: "调研报告",
    desc: "整理调研数据、分析结果和提出建议。",
    color: "bg-teal-500",
  },
  {
    id: 1109,
    icon: "📑",
    title: "转正申请报告",
    desc: "总结试用期工作表现，申请正式转正。",
    color: "bg-cyan-500",
  },
  {
    id: 1110,
    icon: "💡",
    title: "培训总结报告",
    desc: "总结培训内容、收获和应用计划。",
    color: "bg-yellow-500",
  },
  {
    id: 1111,
    icon: "📊",
    title: "业绩分析报告",
    desc: "分析业绩数据、达成情况和改进措施。",
    color: "bg-lime-500",
  },
  {
    id: 1112,
    icon: "🎓",
    title: "学习心得体会",
    desc: "分享学习过程中的思考、感悟和收获。",
    color: "bg-amber-500",
  },
  {
    id: 1113,
    icon: "🏆",
    title: "竞赛总结报告",
    desc: "总结竞赛过程、成绩和经验教训。",
    color: "bg-violet-500",
  },
  {
    id: 1114,
    icon: "📈",
    title: "绩效考核总结",
    desc: "总结考核期工作表现和目标达成情况。",
    color: "bg-rose-500",
  },
];

// 演讲发言模板
export const speechesTemplates = [
  {
    id: 1201,
    icon: "🎤",
    title: "开幕致辞",
    desc: "撰写隆重得体的会议或活动开幕致辞。",
    color: "bg-blue-500",
  },
  {
    id: 1202,
    icon: "🎙️",
    title: "闭幕致辞",
    desc: "总结活动成果，表达感谢和展望未来。",
    color: "bg-green-500",
  },
  {
    id: 1203,
    icon: "👔",
    title: "竞聘演讲",
    desc: "展示个人优势和能力，争取竞聘成功。",
    color: "bg-purple-500",
  },
  {
    id: 1204,
    icon: "🏅",
    title: "获奖感言",
    desc: "表达获奖感受、感谢和未来展望。",
    color: "bg-orange-500",
  },
  {
    id: 1205,
    icon: "🎓",
    title: "毕业致辞",
    desc: "回顾学习历程，展望美好未来。",
    color: "bg-red-500",
  },
  {
    id: 1206,
    icon: "💼",
    title: "新员工欢迎词",
    desc: "欢迎新同事加入，介绍团队文化。",
    color: "bg-indigo-500",
  },
  {
    id: 1207,
    icon: "🎉",
    title: "年会发言稿",
    desc: "总结年度成就，激励团队士气。",
    color: "bg-pink-500",
  },
  {
    id: 1208,
    icon: "📢",
    title: "产品发布演讲",
    desc: "介绍产品特点、优势和市场价值。",
    color: "bg-teal-500",
  },
  {
    id: 1209,
    icon: "🤝",
    title: "合作签约致辞",
    desc: "表达合作意愿，展望共赢未来。",
    color: "bg-cyan-500",
  },
  {
    id: 1210,
    icon: "🎯",
    title: "团队动员讲话",
    desc: "激励团队士气，明确目标和方向。",
    color: "bg-yellow-500",
  },
  {
    id: 1211,
    icon: "🏆",
    title: "表彰大会发言",
    desc: "肯定成绩，激励先进，推动发展。",
    color: "bg-lime-500",
  },
  {
    id: 1212,
    icon: "📚",
    title: "培训开班讲话",
    desc: "强调培训重要性，提出学习要求。",
    color: "bg-amber-500",
  },
  {
    id: 1213,
    icon: "🌟",
    title: "主题演讲稿",
    desc: "围绕特定主题，展开深入阐述和观点分享。",
    color: "bg-violet-500",
  },
];

// 团队管理模板
export const teamManagementTemplates = [
  {
    id: 1301,
    icon: "👥",
    title: "团队建设方案",
    desc: "制定团队建设计划，增强团队凝聚力。",
    color: "bg-blue-500",
  },
  {
    id: 1302,
    icon: "📋",
    title: "绩效考核方案",
    desc: "设计公平合理的绩效考核体系。",
    color: "bg-green-500",
  },
  {
    id: 1303,
    icon: "🎯",
    title: "目标管理计划",
    desc: "制定团队目标，分解任务和考核指标。",
    color: "bg-purple-500",
  },
  {
    id: 1304,
    icon: "📊",
    title: "人员配置方案",
    desc: "优化人员结构，合理配置团队资源。",
    color: "bg-orange-500",
  },
  {
    id: 1305,
    icon: "💡",
    title: "激励方案设计",
    desc: "设计有效的激励机制，提升团队积极性。",
    color: "bg-red-500",
  },
  {
    id: 1306,
    icon: "📚",
    title: "培训计划方案",
    desc: "制定系统的团队培训和发展计划。",
    color: "bg-indigo-500",
  },
  {
    id: 1307,
    icon: "🔄",
    title: "轮岗培养计划",
    desc: "设计轮岗方案，培养复合型人才。",
    color: "bg-pink-500",
  },
  {
    id: 1308,
    icon: "⚖️",
    title: "冲突调解方案",
    desc: "处理团队冲突，维护和谐工作氛围。",
    color: "bg-teal-500",
  },
  {
    id: 1309,
    icon: "📈",
    title: "新人培养计划",
    desc: "制定新员工培养路径和成长计划。",
    color: "bg-cyan-500",
  },
  {
    id: 1310,
    icon: "🎓",
    title: "导师制度方案",
    desc: "建立导师带教机制，加速人才成长。",
    color: "bg-yellow-500",
  },
  {
    id: 1311,
    icon: "🏅",
    title: "晋升管理制度",
    desc: "制定清晰的晋升通道和评定标准。",
    color: "bg-lime-500",
  },
  {
    id: 1312,
    icon: "💼",
    title: "离职面谈指南",
    desc: "规范离职流程，收集改进意见。",
    color: "bg-amber-500",
  },
  {
    id: 1313,
    icon: "🤝",
    title: "团队协作规范",
    desc: "制定团队协作标准和工作流程。",
    color: "bg-violet-500",
  },
  {
    id: 1314,
    icon: "⏰",
    title: "考勤管理制度",
    desc: "制定考勤规则，规范工作时间管理。",
    color: "bg-rose-500",
  },
  {
    id: 1315,
    icon: "🎪",
    title: "团建活动方案",
    desc: "策划有趣的团建活动，增进团队感情。",
    color: "bg-sky-500",
  },
  {
    id: 1316,
    icon: "📝",
    title: "工作职责说明",
    desc: "明确岗位职责和工作要求。",
    color: "bg-emerald-500",
  },
  {
    id: 1317,
    icon: "🔍",
    title: "人才盘点报告",
    desc: "评估团队人才状况，识别关键人才。",
    color: "bg-fuchsia-500",
  },
];

// 项目管理模板
export const projectManagementTemplates = [
  {
    id: 1401,
    icon: "📋",
    title: "项目计划书",
    desc: "制定详细的项目计划，明确目标和资源。",
    color: "bg-blue-500",
  },
  {
    id: 1402,
    icon: "⚡",
    title: "项目启动方案",
    desc: "规划项目启动流程，组建项目团队。",
    color: "bg-green-500",
  },
  {
    id: 1403,
    icon: "📊",
    title: "项目进度报告",
    desc: "跟踪项目进展，及时汇报项目状态。",
    color: "bg-purple-500",
  },
  {
    id: 1404,
    icon: "⚠️",
    title: "风险管理方案",
    desc: "识别项目风险，制定应对措施。",
    color: "bg-orange-500",
  },
  {
    id: 1405,
    icon: "✅",
    title: "项目验收报告",
    desc: "总结项目成果，进行项目验收评估。",
    color: "bg-red-500",
  },
  {
    id: 1406,
    icon: "🔄",
    title: "变更管理流程",
    desc: "规范项目变更管理，控制变更影响。",
    color: "bg-indigo-500",
  },
];

// 个人发展模板
export const personalDevelopmentTemplates = [
  {
    id: 1501,
    icon: "🎯",
    title: "个人发展规划",
    desc: "制定清晰的职业发展目标和实现路径。",
    color: "bg-blue-500",
  },
  {
    id: 1502,
    icon: "📝",
    title: "简历优化",
    desc: "打造专业简历,突出个人优势和成就。",
    color: "bg-green-500",
  },
  {
    id: 1503,
    icon: "💼",
    title: "求职信撰写",
    desc: "撰写有吸引力的求职信，展现求职诚意。",
    color: "bg-purple-500",
  },
  {
    id: 1504,
    icon: "🎓",
    title: "学习计划制定",
    desc: "规划系统的学习路径，提升专业能力。",
    color: "bg-orange-500",
  },
  {
    id: 1505,
    icon: "📚",
    title: "读书笔记整理",
    desc: "记录阅读心得，内化知识精华。",
    color: "bg-red-500",
  },
  {
    id: 1506,
    icon: "🏆",
    title: "自我评估报告",
    desc: "客观评估自身优劣势，明确改进方向。",
    color: "bg-indigo-500",
  },
  {
    id: 1507,
    icon: "💡",
    title: "技能提升计划",
    desc: "识别技能差距，制定针对性提升方案。",
    color: "bg-pink-500",
  },
  {
    id: 1508,
    icon: "🎤",
    title: "面试准备指南",
    desc: "准备面试常见问题，提升面试表现。",
    color: "bg-teal-500",
  },
  {
    id: 1509,
    icon: "📈",
    title: "职业转型规划",
    desc: "规划职业转型路径，实现职业跨越。",
    color: "bg-cyan-500",
  },
  {
    id: 1510,
    icon: "🌟",
    title: "个人品牌建设",
    desc: "打造个人影响力，提升职场竞争力。",
    color: "bg-yellow-500",
  },
  {
    id: 1511,
    icon: "🔍",
    title: "行业研究报告",
    desc: "深入研究行业趋势，把握发展机会。",
    color: "bg-lime-500",
  },
  {
    id: 1512,
    icon: "💪",
    title: "能力测评分析",
    desc: "评估个人能力水平，发现提升空间。",
    color: "bg-amber-500",
  },
  {
    id: 1513,
    icon: "🎯",
    title: "目标达成计划",
    desc: "分解目标为可执行步骤，确保目标实现。",
    color: "bg-violet-500",
  },
  {
    id: 1514,
    icon: "📊",
    title: "时间管理方案",
    desc: "优化时间分配，提升工作效率。",
    color: "bg-rose-500",
  },
  {
    id: 1515,
    icon: "🤝",
    title: "人脉拓展计划",
    desc: "建立和维护职业人脉网络。",
    color: "bg-sky-500",
  },
  {
    id: 1516,
    icon: "💬",
    title: "沟通技巧提升",
    desc: "改善沟通方式，增强表达能力。",
    color: "bg-emerald-500",
  },
  {
    id: 1517,
    icon: "🧘",
    title: "工作生活平衡",
    desc: "平衡工作与生活，保持身心健康。",
    color: "bg-fuchsia-500",
  },
  {
    id: 1518,
    icon: "📖",
    title: "知识体系构建",
    desc: "建立系统的知识框架，形成专业优势。",
    color: "bg-slate-500",
  },
];

// ========== 政务公文模板 ==========

// 政务公文模板
export const governmentAffairsTemplates = [
  {
    id: 2001,
    icon: "📄",
    title: "通知",
    desc: "发布政务通知，传达上级指示和工作安排。",
    color: "bg-blue-500",
  },
  {
    id: 2002,
    icon: "📋",
    title: "通报",
    desc: "通报重要情况、先进事迹或问题警示。",
    color: "bg-green-500",
  },
  {
    id: 2003,
    icon: "📝",
    title: "报告",
    desc: "向上级汇报工作情况、问题和建议。",
    color: "bg-purple-500",
  },
  {
    id: 2004,
    icon: "📃",
    title: "请示",
    desc: "向上级请求指示、批准或支持。",
    color: "bg-orange-500",
  },
  {
    id: 2005,
    icon: "✅",
    title: "批复",
    desc: "对下级请示事项给予答复和指示。",
    color: "bg-red-500",
  },
  {
    id: 2006,
    icon: "📢",
    title: "公告",
    desc: "向社会公众发布重要事项和信息。",
    color: "bg-indigo-500",
  },
  {
    id: 2007,
    icon: "📑",
    title: "决定",
    desc: "对重要事项作出决策和部署。",
    color: "bg-pink-500",
  },
  {
    id: 2008,
    icon: "⚖️",
    title: "意见",
    desc: "对工作提出指导性意见和建议。",
    color: "bg-teal-500",
  },
];

// 事务公文模板
export const administrativeTemplates = [
  {
    id: 2101,
    icon: "📊",
    title: "会议通知",
    desc: "发布会议安排，明确时间地点和参会要求。",
    color: "bg-blue-500",
  },
  {
    id: 2102,
    icon: "📝",
    title: "会议记录",
    desc: "记录会议讨论内容和决议事项。",
    color: "bg-green-500",
  },
  {
    id: 2103,
    icon: "📋",
    title: "工作计划",
    desc: "制定阶段性工作目标和实施方案。",
    color: "bg-purple-500",
  },
  {
    id: 2104,
    icon: "📈",
    title: "工作总结",
    desc: "总结工作成效、经验和存在问题。",
    color: "bg-orange-500",
  },
  {
    id: 2105,
    icon: "🔍",
    title: "调查报告",
    desc: "开展专项调查，分析情况提出建议。",
    color: "bg-red-500",
  },
  {
    id: 2106,
    icon: "📑",
    title: "情况说明",
    desc: "对特定情况进行说明和解释。",
    color: "bg-indigo-500",
  },
  {
    id: 2107,
    icon: "🎯",
    title: "实施方案",
    desc: "制定具体工作的实施步骤和措施。",
    color: "bg-pink-500",
  },
];

// 宣传公文模板
export const publicityTemplates = [
  {
    id: 2201,
    icon: "📢",
    title: "新闻稿",
    desc: "撰写政务新闻，宣传重要工作和成就。",
    color: "bg-blue-500",
  },
  {
    id: 2202,
    icon: "📰",
    title: "简报",
    desc: "编写工作简报，及时反映工作动态。",
    color: "bg-green-500",
  },
  {
    id: 2203,
    icon: "🎙️",
    title: "宣传方案",
    desc: "制定宣传策划，扩大工作影响力。",
    color: "bg-purple-500",
  },
  {
    id: 2204,
    icon: "📝",
    title: "经验材料",
    desc: "总结推广先进经验和典型做法。",
    color: "bg-orange-500",
  },
  {
    id: 2205,
    icon: "🌟",
    title: "典型事迹",
    desc: "宣传先进人物和典型事迹。",
    color: "bg-red-500",
  },
  {
    id: 2206,
    icon: "📣",
    title: "倡议书",
    desc: "发起倡议，号召群众参与和支持。",
    color: "bg-indigo-500",
  },
];

// 通信公文模板
export const communicationDocsTemplates = [
  {
    id: 2301,
    icon: "✉️",
    title: "函",
    desc: "用于不相隶属机关之间商洽工作、询问和答复问题。",
    color: "bg-blue-500",
  },
  {
    id: 2302,
    icon: "💬",
    title: "便函",
    desc: "用于日常工作联系的简便函件。",
    color: "bg-green-500",
  },
  {
    id: 2303,
    icon: "📧",
    title: "联系函",
    desc: "用于单位之间联系具体事务。",
    color: "bg-purple-500",
  },
  {
    id: 2304,
    icon: "🤝",
    title: "协商函",
    desc: "用于就某项工作与其他单位协商。",
    color: "bg-orange-500",
  },
  {
    id: 2305,
    icon: "📮",
    title: "邀请函",
    desc: "邀请相关单位或人员参加活动。",
    color: "bg-red-500",
  },
];

// 礼仪公文模板
export const etiquetteTemplates = [
  {
    id: 2401,
    icon: "🎉",
    title: "贺信",
    desc: "向单位或个人表示祝贺。",
    color: "bg-blue-500",
  },
  {
    id: 2402,
    icon: "🎊",
    title: "贺电",
    desc: "以电报形式表达祝贺之意。",
    color: "bg-green-500",
  },
  {
    id: 2403,
    icon: "🙏",
    title: "慰问信",
    desc: "向有关单位或个人表示慰问。",
    color: "bg-purple-500",
  },
  {
    id: 2404,
    icon: "💐",
    title: "感谢信",
    desc: "对给予帮助和支持的单位或个人表示感谢。",
    color: "bg-orange-500",
  },
  {
    id: 2405,
    icon: "🕊️",
    title: "唁电",
    desc: "对逝者表示哀悼，对家属表示慰问。",
    color: "bg-gray-500",
  },
  {
    id: 2406,
    icon: "🎈",
    title: "欢迎词",
    desc: "欢迎来访客人，表达友好情谊。",
    color: "bg-pink-500",
  },
  {
    id: 2407,
    icon: "👋",
    title: "欢送词",
    desc: "欢送离别客人，表达惜别之情。",
    color: "bg-indigo-500",
  },
  {
    id: 2408,
    icon: "🎤",
    title: "答谢词",
    desc: "对他人的关心和帮助表示感谢。",
    color: "bg-teal-500",
  },
  {
    id: 2409,
    icon: "🎓",
    title: "祝酒词",
    desc: "在宴会等场合发表祝酒讲话。",
    color: "bg-cyan-500",
  },
];
