-- 添加完整的品牌战略类型到conversations表的CHECK约束
ALTER TABLE conversations
DROP CONSTRAINT IF EXISTS conversations_type_check;

ALTER TABLE conversations
ADD CONSTRAINT conversations_type_check
CHECK (type IN (
  'qa', 'role',
  -- 小红书类型
  'xiaohongshu-travel',
  'xiaohongshu-copywriting',
  'xiaohongshu-title',
  'xiaohongshu-profile',
  'xiaohongshu-seo',
  'xiaohongshu-style',
  'xiaohongshu-product',
  'xiaohongshu-recommendation',
  -- 微信类型
  'wechat-article',
  'wechat-outline',
  'wechat-title',
  'wechat-opening',
  -- 头条类型
  'toutiao-article',
  'toutiao-title',
  'toutiao-opening',
  -- 微博类型
  'weibo-post',
  'weibo-topic',
  'weibo-comment',
  -- 知乎类型
  'zhihu-answer',
  'zhihu-article',
  'zhihu-question',
  -- 视频类型
  'video-script',
  'video-opening',
  'video-title',
  -- 私域类型
  'private-circle',
  'private-group',
  'private-personal',
  -- 快手类型
  'kuaishou-script',
  'kuaishou-title',
  'kuaishou-opening',
  -- 抖音类型
  'douyin-script',
  'douyin-title',
  'douyin-opening',
  -- 数据分析类型
  'data-analysis-report',
  'data-analysis-visualization',
  'data-analysis-insight',
  -- 直播类型
  'live-streaming-script',
  'live-streaming-interaction',
  'live-streaming-product-intro',
  -- 汇报总结类型
  'report-work-summary',
  'report-work-plan',
  'report-project-progress',
  'report-sales-performance',
  'report-financial-report',
  'report-market-analysis',
  'report-annual-review',
  'report-probation-review',
  'report-performance-evaluation',
  'report-performance-improvement',
  'report-department-briefing',
  'report-business-development',
  -- 演讲发言类型
  'speeches-onboarding-welcome',
  'speeches-department-intro',
  'speeches-project-kickoff',
  'speeches-team-building-opening',
  'speeches-year-end-summary',
  'speeches-annual-meeting',
  'speeches-award-ceremony',
  'speeches-retirement-farewell',
  'speeches-sales-motivation',
  'speeches-culture-promotion',
  'speeches-onboarding-speech',
  'speeches-probation-review',
  -- 沟通协作类型
  'communication-docs-email',
  'communication-docs-meeting-notice',
  'communication-docs-meeting-minutes',
  'communication-docs-work-report',
  'communication-docs-project-proposal',
  'communication-docs-cooperation-agreement',
  'communication-docs-business-letter',
  'communication-docs-invitation-letter',
  'communication-docs-thank-you-letter',
  'communication-docs-apology-letter',
  'communication-docs-recommendation-letter',
  'communication-docs-complaint-letter',
  'communication-docs-reply-letter',
  -- 团队管理类型
  'team-management-recruitment-ad',
  'team-management-job-description',
  'team-management-interview-invitation',
  'team-management-interview-feedback',
  'team-management-offer-letter',
  'team-management-onboarding-manual',
  'team-management-offboarding-procedure',
  'team-management-career-development',
  'team-management-training-record',
  'team-management-internal-promotion',
  'team-management-transfer-application',
  'team-management-leave-application',
  'team-management-overtime-application',
  'team-management-business-trip-application',
  'team-management-benefits-application',
  'team-management-handover-document',
  -- 项目管理类型
  'project-management-kickoff-report',
  'project-management-plan',
  'project-management-progress-tracking',
  'project-management-communication-plan',
  'project-management-acceptance-report',
  'project-management-post-evaluation',
  -- 个人发展类型
  'personal-development-resume-optimization',
  'personal-development-resume',
  'personal-development-cover-letter',
  'personal-development-growth-plan',
  'personal-development-skill-improvement',
  'personal-development-self-introduction',
  'personal-development-career-planning',
  'personal-development-goal-setting',
  'personal-development-capability-assessment',
  'personal-development-learning-resources',
  'personal-development-certification-application',
  'personal-development-continuing-education',
  'personal-development-mentorship-plan',
  'personal-development-reflection-journal',
  'personal-development-career-transition',
  'personal-development-personal-branding',
  'personal-development-time-management',
  'personal-development-goal-tracking',
  'personal-development-leadership-development',
  -- 政务公文类型
  'government-affairs-resolution',
  'government-affairs-decision',
  'government-affairs-order',
  'government-affairs-communique',
  'government-affairs-announcement',
  'government-affairs-notice',
  'government-affairs-opinion',
  'government-affairs-notification',
  'government-affairs-circular',
  'government-affairs-report',
  'government-affairs-request-for-instructions',
  'government-affairs-reply',
  'government-affairs-proposal',
  'government-affairs-letter',
  'government-affairs-minutes',
  -- 宣传公文类型
  'publicity-press-release',
  'publicity-news-article',
  'publicity-feature-story',
  'publicity-interview-outline',
  'publicity-media-kit',
  'publicity-event-announcement',
  'publicity-promotional-copy',
  'publicity-brand-story',
  'publicity-case-study',
  'publicity-white-paper',
  'publicity-industry-report',
  'publicity-social-media-post',
  -- 事务公文类型
  'administrative-report-material',
  'administrative-inspection-report',
  'administrative-supervision-notice',
  'administrative-evaluation-report',
  'administrative-emergency-plan',
  'administrative-project-application',
  'administrative-contract-agreement',
  'administrative-legal-opinion',
  'administrative-work-plan',
  'administrative-work-summary',
  'administrative-research-report',
  'administrative-meeting-minutes',
  -- 礼仪公文类型
  'etiquette-congratulatory-letter',
  'etiquette-condolence-letter',
  'etiquette-greeting-letter',
  'etiquette-invitation-letter',
  'etiquette-thank-you-letter',
  'etiquette-apology-letter',
  'etiquette-welcome-speech',
  'etiquette-farewell-speech',
  'etiquette-toast-speech',
  'etiquette-opening-remarks',
  'etiquette-closing-remarks',
  'etiquette-introduction-speech',
  -- 品牌战略类型（完整15个）
  'brand-strategy-company-intro',
  'brand-strategy-positioning-slogan',
  'brand-strategy-brand-house',
  'brand-strategy-positioning-report',
  'brand-strategy-vision-mission',
  'brand-strategy-value-proposition',
  'brand-strategy-positioning-map',
  'brand-strategy-architecture',
  'brand-strategy-story-narrative',
  'brand-strategy-audience-analysis',
  'brand-strategy-competitor-analysis',
  'brand-strategy-differentiation',
  'brand-strategy-extension-plan',
  'brand-strategy-risk-management',
  'brand-strategy-annual-plan',
  -- 创意策略类型
  'creative-strategy-brief',
  'creative-strategy-proposal',
  'creative-strategy-brand-positioning',
  'creative-strategy-communication',
  'creative-strategy-concept',
  'creative-strategy-annual-plan',
  'creative-strategy-process-guide',
  'creative-strategy-workflow',
  'creative-strategy-review-checklist',
  'creative-strategy-meeting-minutes',
  'creative-strategy-mind-map',
  'creative-strategy-competitor-analysis',
  'creative-strategy-market-trend',
  'creative-strategy-innovation-trend'
));
