-- 添加演讲发言类型到conversations表的CHECK约束
ALTER TABLE conversations
DROP CONSTRAINT IF EXISTS conversations_type_check;

ALTER TABLE conversations
ADD CONSTRAINT conversations_type_check
CHECK (type IN (
  'qa', 'role',
  -- 小红书类型
  'xiaohongshu-travel',
  'xiaohongshu-copywriting',
  'xiaohongshu-title',
  'xiaohongshu-profile',
  'xiaohongshu-seo',
  'xiaohongshu-style',
  'xiaohongshu-product',
  'xiaohongshu-recommendation',
  -- 公众号类型
  'wechat-article',
  'wechat-continue',
  'wechat-title',
  'wechat-clickbait',
  -- 今日头条类型
  'toutiao-article',
  'toutiao-title',
  'toutiao-qa',
  'toutiao-micro',
  'toutiao-outline',
  -- 微博类型
  'weibo-short',
  'weibo-long',
  'weibo-title',
  'weibo-name',
  'weibo-hotspot',
  'weibo-bio',
  'weibo-tweet',
  -- 知乎类型
  'zhihu-qa',
  'zhihu-answer',
  'zhihu-bio',
  'zhihu-tagline',
  'zhihu-username',
  -- 视频文案类型
  'video-script-outline',
  'video-viral-copy',
  'video-viral-title',
  'video-storyboard',
  'video-golden-3sec',
  'video-sales-script',
  'video-soft-ad',
  'video-selling-point',
  'video-hard-ad',
  'video-hook-script',
  'video-question-method',
  'video-technique-amplify',
  'video-data-proof',
  'video-error-point',
  'video-list-method',
  -- 私域运营类型
  'private-daily',
  'private-moments',
  'private-value',
  'private-marketing',
  'private-reply',
  'private-event',
  'private-rules',
  -- 快手运营类型
  'kuaishou-name',
  'kuaishou-live',
  'kuaishou-script',
  'kuaishou-title',
  'kuaishou-profile',
  -- 抖音运营类型
  'douyin-strategy',
  'douyin-title',
  'douyin-script',
  'douyin-profile',
  'douyin-hotspot',
  'douyin-topic',
  'douyin-name',
  -- 数据分析类型
  'data-analysis-video-play',
  'data-analysis-video-audience',
  'data-analysis-live-sales',
  'data-analysis-live-view',
  'data-analysis-video-interaction',
  'data-analysis-video-sales',
  -- 直播话术类型
  'live-product-selling',
  'live-closing',
  'live-basic-product',
  'live-interaction',
  'live-retention',
  'live-combo-product',
  'live-welfare-product',
  'live-urgency',
  'live-ending',
  'live-30min-script',
  'live-sales-script',
  'live-host-growth',
  'live-title-generator',
  -- 汇报总结类型
  'report-work-summary',
  'report-work-plan',
  'report-project-progress',
  'report-sales-performance',
  'report-financial',
  'report-market-analysis',
  'report-annual-review',
  'report-probation-review',
  'report-performance-evaluation',
  'report-performance-improvement',
  'report-department-brief',
  'report-business-development',
  -- 演讲发言类型（新增）
  'speeches-onboarding-welcome',
  'speeches-department-intro',
  'speeches-project-kickoff',
  'speeches-team-building-opening',
  'speeches-year-end-summary',
  'speeches-annual-meeting',
  'speeches-award-ceremony',
  'speeches-retirement-farewell',
  'speeches-sales-motivation',
  'speeches-culture-promotion',
  'speeches-onboarding-speech',
  'speeches-probation-review'
));
