-- 添加团队管理类型到conversations表的CHECK约束
ALTER TABLE conversations
DROP CONSTRAINT IF EXISTS conversations_type_check;

ALTER TABLE conversations
ADD CONSTRAINT conversations_type_check
CHECK (type IN (
  'qa', 'role',
  -- 小红书类型
  'xiaohongshu-travel',
  'xiaohongshu-copywriting',
  'xiaohongshu-title',
  'xiaohongshu-profile',
  'xiaohongshu-seo',
  'xiaohongshu-style',
  'xiaohongshu-product',
  'xiaohongshu-recommendation',
  -- 公众号类型
  'wechat-article',
  'wechat-continue',
  'wechat-title',
  'wechat-clickbait',
  -- 今日头条类型
  'toutiao-article',
  'toutiao-title',
  'toutiao-qa',
  'toutiao-micro',
  'toutiao-outline',
  -- 微博类型
  'weibo-short',
  'weibo-long',
  'weibo-title',
  'weibo-name',
  'weibo-hotspot',
  'weibo-bio',
  'weibo-tweet',
  -- 知乎类型
  'zhihu-qa',
  'zhihu-answer',
  'zhihu-bio',
  'zhihu-tagline',
  'zhihu-username',
  -- 视频文案类型
  'video-script-outline',
  'video-viral-copy',
  'video-viral-title',
  'video-storyboard',
  'video-golden-3sec',
  'video-sales-script',
  'video-soft-ad',
  'video-selling-point',
  'video-hard-ad',
  'video-hook-script',
  'video-question-method',
  'video-technique-amplify',
  'video-data-proof',
  'video-error-point',
  'video-list-method',
  -- 私域运营类型
  'private-daily',
  'private-moments',
  'private-value',
  'private-marketing',
  'private-reply',
  'private-event',
  'private-rules',
  -- 快手运营类型
  'kuaishou-name',
  'kuaishou-live',
  'kuaishou-script',
  'kuaishou-title',
  'kuaishou-profile',
  -- 抖音运营类型
  'douyin-strategy',
  'douyin-title',
  'douyin-script',
  'douyin-profile',
  'douyin-hotspot',
  'douyin-topic',
  'douyin-name',
  -- 数据分析类型
  'data-analysis-video-play',
  'data-analysis-video-audience',
  'data-analysis-video-interaction',
  'data-analysis-video-conversion',
  'data-analysis-live-data',
  'data-analysis-live-audience',
  'data-analysis-live-product',
  'data-analysis-live-interaction',
  -- 直播运营类型
  'live-streaming-script',
  'live-streaming-product-intro',
  'live-streaming-interaction',
  'live-streaming-opening',
  'live-streaming-closing',
  'live-streaming-urgency',
  'live-streaming-objection',
  'live-streaming-retention',
  -- 汇报总结类型
  'report-work-summary',
  'report-project-summary',
  'report-monthly-report',
  'report-quarterly-report',
  'report-annual-report',
  'report-project-report',
  'report-research-report',
  'report-market-analysis',
  'report-competitor-analysis',
  'report-data-report',
  'report-event-summary',
  'report-training-summary',
  -- 演讲发言类型
  'speeches-onboarding-welcome',
  'speeches-department-intro',
  'speeches-project-kickoff',
  'speeches-team-building-opening',
  'speeches-year-end-summary',
  'speeches-annual-meeting',
  'speeches-award-ceremony',
  'speeches-retirement-farewell',
  'speeches-sales-motivation',
  'speeches-culture-promotion',
  'speeches-onboarding-speech',
  'speeches-probation-review',
  -- 团队管理类型（新增）
  'team-management-recruitment-ad',
  'team-management-job-description',
  'team-management-interview-invitation',
  'team-management-interview-feedback'
));
